# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

* Welcome

Welcome to the Miryoku ZMK alpha!

*Please don't redistribute.  If you fork, please make the fork private.*

You've been added as a collaborator to the repo as it's the easiest way to give access.  If you could avoid accidental force pushes to master that'd be great!  You're not expected to contribute but contributions are of course welcome.  In that case please create a new branch and PR.

See the Todo section below, then see https://github.com/manna-harbour/zmk-config/.

Please let me know if you have any issues.

** Todo

The keymap can be used now, but there's still some work needed before release.

*** +Miryoku documentation+

+Miryoku documentation is being moved from the Miryoku QMK repo to the Miryoku repo.  For now, refer to the documentation in Miryoku QMK.+

Miryoku documentation is now at https://github.com/manna-harbour/miryoku.

*** +Miyroku Babel+

+Code generation in Miryoku QMK and Miryoku ZMK is being combined into Miryoku Babel.  At the moment the Miryoku ZMK keymap is generated from [[miryoku/miryoku-zmk-babel.org]].  Refer to the documentation in Miryoku QMK.+

Miryoku Babel is now being used.

*** Add new keyboard control layers

At the moment bluetooth is in the media layer.  See [[miryoku/miryoku-zmk-babel.org#media-medr]].

*** Add ZMK mouse keys

There is a ~mousekeys~ branch with the [[https://github.com/zmkfirmware/zmk/pull/778][mousekeys PR]] enabled and configured.  Use ~CONFIG_ZMK_MOUSE=y~ in Kconfig [[https://github.com/zmkfirmware/zmk/blob/e91fb88eadc8593f430ea04c5f4e11102176eb94/docs/docs/behaviors/mouse-emulation.md][as described]].

In the default branch the mouse layer is using mouse keys on the host.

- X11: https://en.wikipedia.org/wiki/Mouse_keys
- Windows: https://support.microsoft.com/en-us/windows/use-mouse-keys-to-move-the-mouse-pointer-9e0c72c8-b882-7918-8e7b-391fd62adf33
- Mac: https://support.apple.com/en-au/guide/mac-help/mh27469/mac

