# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

* Welcome

Welcome to the Miryoku ZMK private beta!

*Please don't redistribute.  If you fork, please make the fork private.*

See the notes below, then see the main readme at https://github.com/manna-harbour/zmk-config/.

Please let me know if you have any issues.


** Caveats


*** Collaborator Access

You've been added as a collaborator to the repository in order to give access.  *There's no branch protection so please take care when pushing*.  In particular the GitHub web interface seems to encourage pushing upstream, so please take extra care if using that.  It is generally advised to use a feature branch instead of ~master~ for local changes, and that will also help avoid accidental modifications upstream when merging.


*** Repository Location

The public release will be at https://github.com/manna-harbour/miryoku_zmk/ and will be linked from https://github.com/manna-harbour/miryoku.

There may be some links in the readme already pointing to the public repository and they will be broken until release.


** Todo

Everything can be used now, but there's still some work needed before public release.  See https://github.com/manna-harbour/miryoku/issues/50 for details.


** 

[[https://github.com/manna-harbour][https://raw.githubusercontent.com/manna-harbour/miryoku/master/data/logos/manna-harbour-boa-32.png]]
