
default:
	cd ${HOME}/tmp/src/github/manna-harbour/zmk/app && ZEPHYR_TOOLCHAIN_VARIANT=zephyr ZEPHYR_SDK_INSTALL_DIR=/home/amb/tmp/apps/zephyr-sdk-0.11.2 ${HOME}/.local/bin/west  build -d build/left -b nice_nano -- -DSHIELD=corne_left -DZMK_CONFIG=${HOME}/tmp/src/github/manna-harbour/zmk-config/config


# nice_nano.dts.pre.tmp is in app/build/left/zephyr
