
default:
	cd ${HOME}/tmp/src/github/manna-harbour/zmk/app && ${HOME}/.local/bin/west build -d build/left -b nice_nano -- -DSHIELD=corne_left -DZMK_CONFIG=${HOME}/tmp/src/github/manna-harbour/zmk-config/config/
