# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'My nice!nano_v2 with mirioku'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right","settings_reset"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y","CONFIG_BT_CTLR_TX_PWR_PLUS_8=y","CONFIG_WS2812_STRIP=y"]'
      alphas: '["colemakdhk"]'

