# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Forager'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["forager_left", "forager_right"]'
      alphas: '["qwerty"]'
      extra: '["colemakdh"]'
