# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: '0 My nice!nano_v2 with mirioku'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\n"]'
      custom_config: '["#define MIRYOKU_TAP_QWERTY\n"]'
