# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test All Configs'
on: workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left"]'
      alphas: '[
        "default",
        "azerty",
        "beakl15",
        "colemak",
        "colemakdhk",
        "dvorak",
        "halmak",
        "qwerty",
        "qwertz",
        "workman"
      ]'
      extra: '[
        "default",
        "azerty",
        "beakl15",
        "colemak",
        "colemakdhk",
        "dvorak",
        "halmak",
        "qwerty",
        "qwertz",
        "workman"
      ]'
      tap: '[
        "default",
        "azerty",
        "beakl15",
        "colemak",
        "colemakdhk",
        "dvorak",
        "halmak",
        "qwerty",
        "qwertz",
        "workman"
      ]'
      nav: '[
        "default",
        "invertedt",
        "vi"
      ]'
      clipboard: '[
        "default",
        "fun",
        "mac",
        "win"
      ]'
      layers: '[
        "default",
        "flip"
      ]'
