# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test All Promicro Shields'
on: workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '[
        "a_dux_left","a_dux_right",
        "absolem",
        "ahokore",
        "arch36_left","arch36_right",
        "barobord",
        "bastyl_left","bastyl_right",
        "bat43",
        "berylline_left","berylline_right",
        "breeze_left","breeze_right",
        "chocv",
        "clog_left","clog_right",
        "contra",
        "corne_left","corne_right",
        "cradio_left","cradio_right",
        "crbn",
        "dactyl_manuform_4x5_left","dactyl_manuform_4x5_right",
        "dilemma_left","dilemma_right",
        "draculad_left","draculad_right",
        "eek",
        "elephant42_left","elephant42_right",
        "ergodash_left","ergodash_right",
        "ergotravel_left","ergotravel_right",
        "ffkb",
        "gatoraid40",
        "choc-corne_left","choc-corne_right",
        "helix_left","helix_right",
        "hillside48_left","hillside48_right",
        "horizon",
        "humla",
        "iris_left","iris_right",
        "jian_left","jian_right",
        "jiran_left","jiran_right",
        "jorne_left","jorne_right",
        "klor_left","klor_right",
        "klotz_left","klotz_right",
        "kyria_left","kyria_right",
        "kyria_rev2_left","kyria_rev2_right",
        "kyria_rev3_left","kyria_rev3_right",
        "leeloo_left","leeloo_right",
        "levinson_left","levinson_right",
        "lily58_left","lily58_right",
        "lotus58_left","lotus58_right",
        "luna_left","luna_right",
        "mano42_left","mano42_right",
        "microdox_left","microdox_right",
        "microdox_v2_left","microdox_v2_right",
        "microdox_mod_left","microdox_mod_right",
        "naked60",
        "osprette",
        "otg_left","otg_right",
        "pinkiesout",
        "pockettype",
        "pteron36_left","pteron36_right",
        "rae_dux_left","rae_dux_right",
        "rebound_v4",
        "redox_left","redox_right",
        "reviung39",
        "reviung41",
        "rockon",
        "rollow_left","rollow_right",
        "scylla_dmmpcb_left","scylla_dmmpcb_right",
        "sofle_left","sofle_right",
        "sofle_rgb_left","sofle_rgb_right",
        "splitkb_aurora_corne_left","splitkb_aurora_corne_right",
        "splitkb_aurora_lily58_left","splitkb_aurora_lily58_right",
        "splitkb_aurora_sweep_left","splitkb_aurora_sweep_right",
        "splitreus62_left","splitreus62_right",
        "swweeep_left","swweeep_right",
        "tbkmini_left","tbkmini_right",
        "tbkmini_adapterv2_left","tbkmini_adapterv2_right",
        "temper_left","temper_right",
        "tightyl_left","tightyl_right",
        "viterbi_left","viterbi_right",
        "waterfowl_left","waterfowl_right",
        "xmk",
        "zodiark_left","zodiark_right"
      ]'
