# Copyright 2023 vbn
# https://github.com/vbn/miryoku_zmk

name: 'vbn-swweeep-build'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["swweeep_left nice_view_adapter nice_view","swweeep_right nice_view_adapter nice_view"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_MOUSE=y"]'
      branches: '["petejohanson/zmk/zephyr/3.1-upgrade urob/zmk/mouse-3.2"]'
